In [11]:
import requests
import pandas as pd
import numpy as np

In [62]:
url = 'https://500.farm/vastai-exporter/offers'

r = requests.pop(url)
r.raise_for_status()
rows = r.json()["offers"]

print(r.json()['timestamp'])

raw  = pd.DataFrame(rows)
raw['timestamp'] = r.json()['timestamp']

raw.head()

2023-07-30T05:57:03.144732606Z


bundle_id  bw_nvlink  compute_cap  cpu_cores  cpu_cores_effective  \
0  314697833        0.0          890      256.0                256.0   
1  314697840        0.0          890      256.0                256.0   
2  314525846        0.0          890      192.0                192.0   
3  314696316        0.0          890      256.0                256.0   
4  314697828        0.0          890      256.0                256.0   

                          cpu_name  cpu_ram credit_balance credit_discount  \
0  AMD EPYC 7H12 64-Core Processor   515762           None            None   
1  AMD EPYC 7662 64-Core Processor   515762           None            None   
2  AMD EPYC 7R12 48-Core Processor   515814           None            None   
3  AMD EPYC 7742 64-Core Processor   515776           None            None   
4  AMD EPYC 7742 64-Core Processor   515841           None            None   

   credit_discount_max  ...  reliability2  rentable      score  start_date  \
0                  0.4  ...      0.979890     False  16.504390         NaN   
1                  0.4  ...      0.979650     False  16.138499         NaN   
2                  0.4  ...      0.991366     False  25.629089         NaN   
3                  0.2  ...      0.996083     False  27.217322         NaN   
4                  0.4  ...      0.982960     False  21.980601         NaN   

   static_ip  storage_cost total_flops  verification  verified  \
0       True          0.15  1438.18752      verified      True   
1       True          0.15  1436.22144      verified      True   
2       True          0.35  1431.30624      verified      True   
3       True          0.25  1429.34016      verified      True   
4       True          0.15  1227.81696      verified      True   

                        timestamp  
0  2023-07-30T05:57:03.144732606Z  
1  2023-07-30T05:57:03.144732606Z  
2  2023-07-30T05:57:03.144732606Z  
3  2023-07-30T05:57:03.144732606Z  
4  2023-07-30T05:57:03.144732606Z  

[5 rows x 58 columns]

In [3]:
# raw.duration = raw.duration.apply(lambda x: pd.to_timedelta(x * 1e9).days)
# raw[['start_date', 'end_date']] = raw[['start_date', 'end_date']].apply(lambda x: pd.to_datetime(x * 1e9))

In [4]:
raw.columns

Index(['bundle_id', 'bw_nvlink', 'compute_cap', 'cpu_cores',
       'cpu_cores_effective', 'cpu_name', 'cpu_ram', 'credit_balance',
       'credit_discount', 'credit_discount_max', 'cuda_max_good',
       'direct_port_count', 'discount_rate', 'discounted_dph_total',
       'discounted_hourly', 'disk_bw', 'disk_name', 'disk_space', 'dlperf',
       'dlperf_per_dphtotal', 'dph_base', 'driver_version', 'duration',
       'end_date', 'flops_per_dphtotal', 'geolocation', 'gpu_display_active',
       'gpu_frac', 'gpu_lanes', 'gpu_mem_bw', 'gpu_name', 'gpu_ram', 'has_avx',
       'host_id', 'host_run_time', 'hosting_type', 'id', 'inet_down',
       'inet_down_cost', 'inet_up', 'inet_up_cost', 'machine_id', 'min_bid',
       'mobo_name', 'num_gpus', 'pci_gen', 'pcie_bw', 'public_ipaddr',
       'reliability2', 'rentable', 'score', 'start_date', 'static_ip',
       'storage_cost', 'total_flops', 'verification', 'verified', 'timestamp'],
      dtype='object')

In [5]:
to_drop = ['bundle_id']
cols = [c for c in raw.columns.tolist() if c not in to_drop]
# cols = raw.columns.tolist()

raw[cols]\
    .set_index(['host_id', 'machine_id', 'id'])\
    .sort_index()

bw_nvlink  compute_cap  cpu_cores  \
host_id machine_id id                                           
18      1569       6293285   0.000000          890      256.0   
        2744       6582981   0.000000          890      128.0   
                   6582982   0.000000          890      128.0   
                   6582983   0.000000          890      128.0   
        2980       6334086  56.248001          860      128.0   
...                               ...          ...        ...   
75261   11823      6637010   0.000000          860       56.0   
                   6637011   0.000000          860       56.0   
                   6637012   0.000000          860       56.0   
                   6637013   0.000000          860       56.0   
                   6637014   0.000000          860       56.0   

                            cpu_cores_effective  \
host_id machine_id id                             
18      1569       6293285           256.000000   
        2744       6582981           128.000000   
                   6582982            64.000000   
                   6582983            64.000000   
        2980       6334086           128.000000   
...                                         ...   
75261   11823      6637010            18.666648   
                   6637011            56.000000   
                   6637012            18.666648   
                   6637013            37.333352   
                   6637014            18.666648   

                                                   cpu_name  cpu_ram  \
host_id machine_id id                                                  
18      1569       6293285  AMD EPYC 7B13 64-Core Processor   515771   
        2744       6582981  AMD EPYC 7452 32-Core Processor   515820   
                   6582982  AMD EPYC 7452 32-Core Processor   515820   
                   6582983  AMD EPYC 7452 32-Core Processor   515820   
        2980       6334086  AMD EPYC 7452 32-Core Processor   515818   
...                                                     ...      ...   
75261   11823      6637010                Xeon® E5-2680 v4    257810   
                   6637011                Xeon® E5-2680 v4    257810   
                   6637012                Xeon® E5-2680 v4    257810   
                   6637013                Xeon® E5-2680 v4    257810   
                   6637014                Xeon® E5-2680 v4    257810   

                           credit_balance credit_discount  \
host_id machine_id id                                       
18      1569       6293285           None            None   
        2744       6582981           None            None   
                   6582982           None            None   
                   6582983           None            None   
        2980       6334086           None            None   
...                                   ...             ...   
75261   11823      6637010           None            None   
                   6637011           None            None   
                   6637012           None            None   
                   6637013           None            None   
                   6637014           None            None   

                            credit_discount_max  cuda_max_good  ...  \
host_id machine_id id                                           ...   
18      1569       6293285                  NaN           12.0  ...   
        2744       6582981                  0.2           12.0  ...   
                   6582982                  0.2           12.0  ...   
                   6582983                  0.2           12.0  ...   
        2980       6334086                  NaN           12.0  ...   
...                                         ...            ...  ...   
75261   11823      6637010                  0.4           12.0  ...   
                   6637011                  0.4           12.0  ...   
                   6637012                  0.4           12.0  ...   
      

In [6]:
def pd_min_chunk(df):
    gpu_chunks = list(df.num_gpus)
    gpu_chunks.sort()
    min_chunk = min(gpu_chunks)

    # correction for the case where whole machine size is not a multiple of min_chunk
    # in this case, there is always a single remainder chunk which is smaller than actual min_chunk
    # examples: [1 2 2 2 3 4 7] [1 2 3], actual min_chunk is 2
    #           [3 4 7], actual min_chunk is 4
    if gpu_chunks.count(min_chunk) == 1 and len(gpu_chunks) >= 3:
        min_chunk = gpu_chunks[1]

    # filter undivided chunks
    undivided = df[df.num_gpus <= min_chunk]
    return undivided

df = raw.groupby('machine_id')\
    .apply(pd_min_chunk)\
    .set_index(['host_id', 'machine_id', 'id']) \
    .sort_index()
df

bundle_id  bw_nvlink  compute_cap  cpu_cores  \
host_id machine_id id                                                      
18      1569       6293285  313990899   0.000000          890      256.0   
        2744       6582982  314494521   0.000000          890      128.0   
                   6582983  314494521   0.000000          890      128.0   
        2980       6334086  314545753  56.248001          860      128.0   
        3090       5763835  313990052   0.000000          860       96.0   
...                               ...        ...          ...        ...   
75192   11818      6634416  314693442   0.000000          890       64.0   
                   6634419  314693442   0.000000          890       64.0   
75261   11823      6637010  314707395   0.000000          860       56.0   
                   6637012  314707395   0.000000          860       56.0   
                   6637014  314707395   0.000000          860       56.0   

                            cpu_cores_effective  \
host_id machine_id id                             
18      1569       6293285           256.000000   
        2744       6582982            64.000000   
                   6582983            64.000000   
        2980       6334086           128.000000   
        3090       5763835            96.000000   
...                                         ...   
75192   11818      6634416            10.666688   
                   6634419            10.666688   
75261   11823      6637010            18.666648   
                   6637012            18.666648   
                   6637014            18.666648   

                                                   cpu_name  cpu_ram  \
host_id machine_id id                                                  
18      1569       6293285  AMD EPYC 7B13 64-Core Processor   515771   
        2744       6582982  AMD EPYC 7452 32-Core Processor   515820   
                   6582983  AMD EPYC 7452 32-Core Processor   515820   
        2980       6334086  AMD EPYC 7452 32-Core Processor   515818   
        3090       5763835  AMD EPYC 7402 24-Core Processor   515837   
...                                                     ...      ...   
75192   11818      6634416  AMD EPYC 7542 32-Core Processor   515667   
                   6634419  AMD EPYC 7542 32-Core Processor   515667   
75261   11823      6637010                Xeon® E5-2680 v4    257810   
                   6637012                Xeon® E5-2680 v4    257810   
                   6637014                Xeon® E5-2680 v4    257810   

                           credit_balance credit_discount  \
host_id machine_id id                                       
18      1569       6293285           None            None   
        2744       6582982           None            None   
                   6582983           None            None   
        2980       6334086           None            None   
        3090       5763835           None            None   
...                                   ...             ...   
75192   11818      6634416           None            None   
                   6634419           None            None   
75261   11823      6637010           None            None   
                   6637012           None            None   
                   6637014           None            None   

                            credit_discount_max  ...  reliability2  rentable  \
host_id machine_id id                            ...                           
18      1569       6293285                  NaN  ...      0.999085     False   
        2744       6582982                  0.2  ...      0.999059     False   
                   6582983                  0.2  ...      0.999059     False   
        2980       6334086                  NaN  ...      0.997181     False   
        3090       5763835                  NaN  ...      0.993133     False   
...                                         ...  ...           ...       ...   
7519

In [10]:
raw.set_index(['host_id', 'machine_id', 'id']).sort_index()['num_gpus']

host_id  machine_id  id     
18       1569        6293285    8
         2744        6582981    8
                     6582982    4
                     6582983    4
         2980        6334086    8
                               ..
75261    11823       6637010    2
                     6637011    6
                     6637012    2
                     6637013    4
                     6637014    2
Name: num_gpus, Length: 5330, dtype: int64

In [8]:
df['num_gpus']

host_id  machine_id  id     
18       1569        6293285    8
         2744        6582982    4
                     6582983    4
         2980        6334086    8
         3090        5763835    8
                               ..
75192    11818       6634416    1
                     6634419    1
75261    11823       6637010    2
                     6637012    2
                     6637014    2
Name: num_gpus, Length: 3276, dtype: int64

In [318]:
def group_by_min(values, ids):
    argidx = np.argsort(ids)
    ids_sort, values_sort = ids[argidx], values[argidx]
    slice_ids = np.r_[0, np.flatnonzero(np.diff(ids_sort)) + 1]
    return np.minimum.reduceat(values_sort, slice_ids)

In [319]:
min_gpus = raw.groupby('machine_id')['num_gpus'].min()
np.all(min_gpus == group_by_min(raw.num_gpus.values, raw.machine_id.values))

True

In [320]:
%timeit raw.groupby('machine_id')['num_gpus'].min()
%timeit group_by_min(raw.num_gpus.values, raw.machine_id.values)

448 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
170 µs ± 1.02 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [321]:
%timeit raw.sort_values(by=['machine_id', 'num_gpus'])
%timeit np.lexsort((raw.num_gpus.values, raw.machine_id.values))

2.32 ms ± 171 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
245 µs ± 852 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [308]:
# raw.sort_values(by='machine_id', inplace=True)
# slice_idx = np.r_[0, np.flatnonzero(np.diff(raw.machine_id.values)) + 1]
# np.all(np.minimum.reduceat(raw.num_gpus.values, slice_idx) == raw.groupby('machine_id')['num_gpus'].min())

True

In [322]:
lexidx = np.lexsort((raw.num_gpus.values, raw.machine_id.values))
np.hstack([raw.machine_id.values[lexidx][:, np.newaxis], raw.num_gpus.values[lexidx][:, np.newaxis]])

array([[  274,     1],
       [  274,     1],
       [  274,     1],
       ...,
       [11462,     1],
       [11462,     2],
       [11463,     1]], dtype=int64)

In [323]:
def hstack(a, b):
    return np.hstack([a[:, np.newaxis], b[:, np.newaxis]])

In [340]:
raw[['machine_id', 'num_gpus']]

machine_id  num_gpus
5277         274         1
5275         274         1
4415         274         8
5027         274         4
5199         274         2
...          ...       ...
5086       11461         1
4244       11462         2
4692       11462         1
4693       11462         1
5207       11463         1

[5310 rows x 2 columns]

In [334]:
lexidx

array([   0,    1,    5, ..., 5308, 5306, 5309], dtype=int64)

In [333]:
raw.loc[lexidx, ['machine_id', 'num_gpus']]

machine_id  num_gpus
0          10298        14
1          10163        14
5           7075         8
8          10184         8
9          10116         8
...          ...       ...
5304        7630         1
5307        9528         1
5308       11250         1
5306        7630         1
5309       10914         1

[5310 rows x 2 columns]

In [354]:
raw.loc[lexidx][['machine_id', 'num_gpus']]

machine_id  num_gpus
5274         274         1
5275         274         1
5276         274         1
5277         274         1
5278         274         1
...          ...       ...
4465       11461         2
4694       11462         1
4695       11462         1
4246       11462         2
5208       11463         1

[5311 rows x 2 columns]

In [350]:
lexidx = np.lexsort((raw.num_gpus.values, raw.machine_id.values))
machine_ids, num_gpus = raw.machine_id.values[lexidx], raw.num_gpus.values[lexidx]
slice_idx =  np.r_[0, np.flatnonzero(np.diff(machine_ids)) + 1]
min_chunk = num_gpus[slice_idx]

hstack(machine_ids[slice_idx], min_chunk)
# min_chunks = np.minimum.reduceat(num_gpus, slice_idx)
# min_chunks

array([[  274,     1],
       [  275,     1],
       [  283,     2],
       ...,
       [11461,     1],
       [11462,     1],
       [11463,     1]], dtype=int64)

In [355]:
group_count = np.diff(np.concatenate([slice_idx, [len(machine_ids)]])) # groupby('machine_id').count()

min_chunk_ex = np.repeat(min_chunk, group_count) # expanded min_chunk for each machine_id

min_chunk_count = np.add.reduceat((min_chunk_ex == num_gpus), slice_idx)

# hstack(machine_ids[slice_idx], min_chunk_count)

In [395]:
# calculate second_min_chunk: second-smallest value
# python loop:
# if gpu_chunks.count(min_chunk) == 1 and len(gpu_chunks) >= 3:
#     min_chunk = gpu_chunks[1]
#
# vectorized:
# second_min_idx = num_gpus[slice_idx + 1]

idx = (min_chunk_count == 1) & (group_count >= 3)
second_min_idx = slice_idx + 1
if second_min_idx[-1] == machine_ids.size:
    second_min_idx[-1] -= 1
min_chunk[idx] = num_gpus[second_min_idx][idx]

hstack(machine_ids[slice_idx][idx], min_chunk[idx])

array([[ 3690,     3],
       [ 4555,     2],
       [ 4708,     2],
       [ 7067,     2],
       [ 7448,     2],
       [ 7471,     2],
       [ 8384,     3],
       [ 8754,     2],
       [ 8888,     2],
       [ 9232,     2],
       [10298,     4],
       [10330,     2],
       [10456,     2],
       [10457,     2],
       [10469,     4],
       [11163,     4],
       [11309,     2],
       [11362,     2],
       [11397,     2],
       [11441,     4],
       [11446,     4]], dtype=int64)

In [358]:
# update min_chunk_ex
min_chunk_ex = np.repeat(min_chunk, group_count)
min_chunk_ex

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [379]:

np_arr = raw.loc[lexidx][num_gpus <= min_chunk_ex][['machine_id', 'num_gpus']]
np_arr

machine_id  num_gpus
5274         274         1
5275         274         1
5276         274         1
5277         274         1
5278         274         1
...          ...       ...
5086       11461         1
5087       11461         1
4694       11462         1
4695       11462         1
5208       11463         1

[3245 rows x 2 columns]

In [369]:
df = raw.groupby('machine_id', group_keys=False).apply(pd_min_chunk)[['machine_id', 'num_gpus']]
df

machine_id  num_gpus
5274         274         1
5275         274         1
5276         274         1
5277         274         1
5278         274         1
...          ...       ...
5086       11461         1
5087       11461         1
4694       11462         1
4695       11462         1
5208       11463         1

[3245 rows x 2 columns]

In [380]:
all(df == pd.DataFrame(np_arr, columns=df.columns, index=df.index))

True

In [14]:
def np_min_chunk(raw):
    lexidx = np.lexsort((raw.num_gpus.values, raw.machine_id.values))

    machine_ids, num_gpus = raw.machine_id.values[lexidx], raw.num_gpus.values[lexidx]
    slice_idx =  np.r_[0, np.flatnonzero(np.diff(machine_ids)) + 1]
    group_count = np.diff(np.concatenate([slice_idx, [len(machine_ids)]])) # groupby('machine_id').count()

    min_chunk = num_gpus[slice_idx]
    min_chunk_ex = np.repeat(min_chunk, group_count) # expanded min_chunk for each machine_id
    min_chunk_count = np.add.reduceat((min_chunk_ex == num_gpus), slice_idx)

    # calculate second_min_chunk: second-smallest value
    # python loop:
    # if gpu_chunks.count(min_chunk) == 1 and len(gpu_chunks) >= 3:
    #     min_chunk = gpu_chunks[1]
    #
    # vectorized:
    # second_min_idx = num_gpus[slice_idx + 1]

    idx = (min_chunk_count == 1) & (group_count >= 3)

    second_min_idx = slice_idx + 1
    if second_min_idx[-1] == machine_ids.size:
        second_min_idx[-1] -= 1

    min_chunk[idx] = num_gpus[second_min_idx][idx]

    # update min_chunk_ex
    min_chunk_ex = np.repeat(min_chunk, group_count)

    return raw.loc[lexidx][num_gpus <= min_chunk_ex].copy()

In [385]:
df = raw.groupby('machine_id', group_keys=False).apply(pd_min_chunk)
df

bundle_id  bw_nvlink  compute_cap  cpu_cores  cpu_cores_effective  \
5274  314265729        0.0          610       32.0                  4.0   
5275  314265729        0.0          610       32.0                  4.0   
5276  314265729        0.0          610       32.0                  4.0   
5277  314265729        0.0          610       32.0                  4.0   
5278  314265729        0.0          610       32.0                  4.0   
...         ...        ...          ...        ...                  ...   
5086  314312977        0.0          860        2.0                  1.0   
5087  314312977        0.0          860        2.0                  1.0   
4694  314315732        0.0          860       24.0                 12.0   
4695  314315732        0.0          860       24.0                 12.0   
5208  314316075        0.0          860       28.0                 28.0   

                             cpu_name  cpu_ram credit_balance credit_discount  \
5274                Xeon® E5-2650 v2     64377           None            None   
5275                Xeon® E5-2650 v2     64377           None            None   
5276                Xeon® E5-2650 v2     64377           None            None   
5277                Xeon® E5-2650 v2     64377           None            None   
5278                Xeon® E5-2650 v2     64377           None            None   
...                               ...      ...            ...             ...   
5086                  Celeron® G3900      7881           None            None   
5087                  Celeron® G3900      7881           None            None   
4694  AMD EPYC 7402 24-Core Processor   515736           None            None   
4695  AMD EPYC 7402 24-Core Processor   515736           None            None   
5208                Xeon® E5-2680 v4     31991           None            None   

      credit_discount_max  ...    public_ipaddr  reliability2  rentable  \
5274                  0.4  ...    194.44.114.10      0.994629     False   
5275                  0.4  ...    194.44.114.10      0.994629      True   
5276                  0.4  ...    194.44.114.10      0.994629      True   
5277                  0.4  ...    194.44.114.10      0.994629      True   
5278                  0.4  ...    194.44.114.10      0.994629      True   
...                   ...  ...              ...           ...       ...   
5086                  0.4  ...  188.239.100.118      0.729967      True   
5087                  0.4  ...  188.239.100.118      0.729967      True   
4694                  0.4  ...    111.30.115.30      0.738135      True   
4695                  0.4  ...    111.30.115.30      0.738135      True   
5208                  0.4  ...  123.149.206.204      0.651718      True   

          score    start_date  storage_cost total_flops  verification  \
5274  48.819962           NaN          0.15     7.67616    deverified   
5275  47.335885  1.688827e+09          0.15     7.67616    deverified   
5276  50.440345  1.688827e+09          0.15     7.67616    deverified   
5277  48.940285  1.688827e+09          0.15     7.67616    deverified   
5278  47.053943  1.688827e+09          0.15     7.67616    deverified   
...         ...           ...           ...         ...           ...   
5086  28.774001  1.688827e+09          0.15    24.72960    unverified   
5087  28.787978  1.688827e+09          0.15    24.72960    unverified   
4694  17.258549  1.688827e+09          0.15    44.08320    unverified   
4695  16.463501  1.688827e+09          0.15    44.08320    unverified   
5208  17.359241  1.688827e+09          0.15    15.05280    unverified   

      verified                       timestamp  
5274     False  2023-07-08T14:35:07.422220185Z  
5275     False  2023-07-08T14:35:07.422220185Z  
5276     False  2023-07-08T14:35:07.422220185Z  
5277     False  2023-07-08T14:35:07.422220185Z  
5278     False  2023-07-08T14:35:07.422220185Z  
...        ...                             ...  
5086     Fa

In [398]:
all(np_min_chunk(raw).sort_index() == df.sort_index())

True

In [403]:
%timeit np_min_chunk(raw)
%timeit raw.groupby('machine_id', group_keys=False).apply(pd_min_chunk)

4.02 ms ± 281 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.87 s ± 7.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Tests

In [19]:
np_min_chunk(raw).machine_id.unique().size

1220

In [18]:
from src.vast_api import get_machines

machines = get_machines()

In [20]:
machines.machine_id.size

1215

In [22]:
np_ids = np_min_chunk(raw).machine_id.unique()
np_ids[~np.isin(np_ids, machines.machine_id)]

array([ 3690,  5919,  6312,  8384, 11693], dtype=int64)

In [80]:
!python vast search offers -h

usage: ./vast search offers [--help] [--api-key API_KEY] [--raw] <query>

positional arguments:
  query                 Query to search for. default: 'external=false
                        rentable=true verified=true', pass -n to ignore
                        default

options:
  -h, --help            show this help message and exit
  -t TYPE, --type TYPE  Show 'bid'(interruptible) or 'on-demand' offers.
                        default: on-demand
  -i, --interruptible   Alias for --type=bid
  -b, --bid             Alias for --type=bid
  -d, --on-demand       Alias for --type=on-demand
  -n, --no-default      Disable default query
  --disable-bundling    Show identical offers. This request is more heavily
                        rate limited.
  --storage STORAGE     Amount of storage to use for pricing, in GiB.
                        default=5.0GiB
  -o ORDER, --order ORDER
                        Comma-separated list of fields to sort on. postfix
                        field with - 

In [81]:
!python vast search offers "machine_id=11693 rentable=any verified=any" -d --disable-bundling

https://console.vast.ai/api/v0/bundles?q=%7B%22external%22%3A+%7B%22eq%22%3A+false%7D%2C+%22machine_id%22%3A+%7B%22eq%22%3A+%2211693%22%7D%2C+%22order%22%3A+%5B%5B%22score%22%2C+%22desc%22%5D%5D%2C+%22type%22%3A+%22on-demand%22%2C+%22disable_bundling%22%3A+true%7D&api_key=6bbc6e308dcf1fb7f0ead78eae9dbfc23767871bf2b8b7e1f3c9b54a99bc1579
{'external': {'eq': False}, 'machine_id': {'eq': '11693'}, 'order': [['score', 'desc']], 'type': 'on-demand', 'disable_bundling': True}
ID       CUDA    N  Model     PCIE  vCPUs    RAM  Disk  $/hr    DLP   DLP/$  NV Driver  Net_up  Net_down  R     Max_Days  mach_id  status      ports  country    
6595177  12.2   4x  RTX_3070  6.4   21.3   257.5  1117  0.4800  45.9  95.65  535.54.03  272.0   272.2     96.4  154.8     11693    unverified  333    Estonia,_EE
6595179  12.2   6x  RTX_3070  6.4   32.0   257.5  1676  0.7200  58.2  80.77  535.54.03  272.0   272.2     96.4  154.8     11693    unverified  500    Estonia,_EE
6595180  12.2   6x  RTX_3070  6.4   32.0

In [ ]:
df_pd = raw.groupby('machine_id', as_index=False).apply(pd_min_chunk).reset_index(drop=True)

In [48]:
df_pd.loc[df_pd.machine_id == 3690, ['id', 'num_gpus', 'rentable']]

id  num_gpus  rentable
422  5516879         1     False
423  5516876         1     False
424  5516875         1     False
425  5516874         1     False
426  5402877         1     False
427  5402874         1     False
428  5402873         1     False
429  5402872         1     False

In [68]:
np_min_chunk(raw).loc[np_min_chunk(raw).machine_id == 8384, ['id', 'num_gpus', 'rentable']]

id  num_gpus  rentable
4698  6519142         2      True
4311  6519145         3      True
4313  6519138         3      True
4314  6519143         3      True
4315  6519140         3      True

In [73]:
raw.loc[raw.machine_id == 11693, ['machine_id', 'id', 'num_gpus', 'rentable']].sort_values('id')

machine_id       id  num_gpus  rentable
4519       11693  6595177         4      True
4092       11693  6595178        12      True
4274       11693  6595179         6      True
4271       11693  6595180         6      True
4212       11693  6595181         8      True